### ISSUE TITLE
-c not recruiting all genomes

### ISSUE THREAD

**Issue by andrewdhuang** [marbl/parsnp#10]
Parsnp seems to be leaving out about a quarter of my assemblies even with the -c flag. We are running assemblies from samples all of the same species, though of differing assembly qualities. Are there selection criteria for assemblies even with -c?

> parsnp -g ../../NC_XXXXXX.gb -d LargeContigs_Mike/ -p 12 -o P_metag_isolates_150511/ -c

**Comment by treangen** [comment]
> Are there selection criteria for assemblies even with -c?

yes, they cannot differ in size by more than (+/-) 30% w.r.t the selected reference genome.

**Comment by andrewdhuang** [comment]
For me that seems to be true in some but not all cases. I have samples that are +26% and +10% that did not get included and one sample that is +48% that did get included.

Is there any way for me to turn off or adjust this %?

**Comment by treangen** [comment]
>For me that seems to be true in some but not all cases.
>I have samples that are +26% and +10% that did not get included and one sample that is +48% that >did get included.

just to clarify, genomes that are (+/-) >=40% w.r.t to reference are excluded, not 30%. This is done simply to quickly filter out unrelated sequences, agree that it should be made available as a parameter.

so one assembly that was +26% larger than the reference was excluded, while an assembly that was +48% larger than the reference was *included*? If so, this definitely shouldn't happen (unless the some of the sequences  are empty or <20bp, in which case they are always removed). would you be willing to share your input dataset (ftp) so that I can debug? 

>Is there any way for me to turn off or adjust this %?

Not currently. I've added this to the list of things to add for the upcoming release (tbd, soon but not imminent). In the meantime, only if you run Parsnp from source, you can directly edit line 676 in the Parsnp.py source file (if sizediff) to ignore the size diff filtering.

**Comment by andrewdhuang** [comment]
I'll inquire if I can share this data set. Might be able to and I'll look more closely at the data too for these things you mentioned.

I'm having a heck of a time attempting to recompile from the source. I know it's a lot to ask, but is there any way you can compile me a version without the % restriction?

**Comment by treangen** [comment]
> I know it's a lot to ask, but is there any way you can compile me a version without the % restriction?

ftp://ftp.cbcb.umd.edu/pub/data/harvest/parsnp_osx_ignoresize.gz

**Comment by andrewdhuang** [comment]
Many thanks! I should have been more specific though. Could you compile it for Linux? Thanks again.

**Comment by treangen** [comment]
ftp://ftp.cbcb.umd.edu/pub/data/harvest/parsnp_linux_ignoresize.gz

**Comment by treangen** [comment]
if the prev parsnp linux binary ran on your system this one should also, but let me know if you run into any issues,

**Comment by andrewdhuang** [comment]
Worked like a charm. Many thanks!

**Comment by jellila** [comment]
> > I know it's a lot to ask, but is there any way you can compile me a version without the % restriction?
> 
> ftp://ftp.cbcb.umd.edu/pub/data/harvest/parsnp_osx_ignoresize.gz

How did you do that, please? :)
