### ISSUE TITLE
Bootstrap values are not showing up in the tree

### ISSUE THREAD

**Issue by naomiohta** [marbl/parsnp#103]
Hello, I am using Parsnp 1.5.3 on MacBook Pro and successfully finished the command as below, but I can't find the bootstrap values.

parsnp -g /Users/myname/reference_ref.gbk -d /Users/myname/serotype_fasta_contigs/*.fasta -c -p 4 -x -o /Users/myname/parsnpout/012422_x 

When I try to visualize the tree file using iTOL and Figtree, they aren't displaying bootstrap values. Am I missing something? 
Thank you!

**Comment by bkille** [comment]
Hi @naomiohta, thanks for opening an issue! Can you see the bootstrap values in the `.tree` file?

**Comment by valery-shap** [comment]
Hello,

I have the same question. and I used the same command.
(one.fasta:0.00000100000050002909,((second.fasta:0.00000100000050002909,third.fasta:0.00000100000050002909):0.00032947413443052423,(((((((((((forth.fasta:0.00165147864484025526,fifth.fasta:0.00115577065595259191):0.00041196000646219347

Assume that these are only branch lengths.
Valery

**Comment by naomiohta** [comment]
Thank you @bkille for your prompt response. 
As @valery-shap showed, I can see similar values in my .tree file. I was thinking those are the bootstrap values, but are they branch lengths?

**Comment by eddykay310** [comment]
Same issue here. I have been trying to understand why it is so if fasttree is used for constructing the tree and if there was a command line option that can be used but I guess yhere is none. 

Thanks in advance for the help

**Comment by bkille** [comment]
@valery-shap, @naomiohta and @eddykay310, thanks for waiting and sorry for the delay. RAxML's default search algorithm no longer uses bootstrapping. If you would like to run RAxML yourself, I've pushed an updated that keeps the `parsnp.snps.mblocks` file, which contains the core SNPs that are to be input to RAxML or FastTree. You can run Parsnp with the `--skip-phylogeny` argument and then run RAxML on the `parsnp.snps.mblocks` file in your output directory using your desired arguments.

Unfortunately, there is currently an [issue](https://github.com/bioconda/bioconda-recipes/issues/33283) in bioconda preventing updates to bioconda tools. I'll reply to this thread once that issue is fixed and Parsnp v1.6.2 is available through conda.

**Comment by valery-shap** [comment]
Hello, 
Thank you for your reply!
One more question: 
Harvest tool has the option of input ggr file and output -S <output for multi-fasta SNPs>.
Isn’t it the same file parsnp.snps.mblocks?

**Comment by bkille** [comment]
Yes, that's correct, thanks! In the meantime you can definitely use `harvesttools` to obtain the multifasta SNP file.

**Comment by naomiohta** [comment]
Thanks so much for the update @bkille. 
I will run without the tree option. I am looking forward to the newer version!

Just to clarify, does Parsnp use RAxML and not FastTree2?

**Comment by bkille** [comment]
Yes, it runs RAxML by default, however you can use FastTree instead by passing the `--use-fasttree` flag.

**Comment by bkille** [comment]
Parsnp v1.6.2 is now available through conda. You can now skip the phylogeny step and then run your own analysis on the `parsnp.snps.mblocks` file.
