### ISSUE TITLE
parsnp: error: the following arguments are required: -d/--sequences

### ISSUE THREAD

**Issue by Phylloxera** [marbl/parsnp#113]
parsnpv1.5.3
`parsnp_linux/parsnp -r England1.fna -d genomes/*.fna -c -p 4 -o test3`
runs fine
`parsnp_linux/parsnp –r CP030241.fasta –d fasta/*.fasta -x YES -o xyes_cno`
gives error in title. any ideas?

**Comment by bkille** [comment]
So the older version of parsnp actually had the xtrafast and phipack flags duplicated, i.e. `-x` would (and still does) activate the recombination detection. I'll update the `--help` documentation in the next release.

As far as getting a more updated binary goes, would you be interested in installing via `conda`? Its been our preferred route for some time, since it makes it easier to ensure that the dependencies are also installed and the correct versions.

**Comment by Phylloxera** [comment]
not a fan of conda... but if I containerize this (singularity), I'll be happy to do via conda within the container.
right now I'm not getting any snps output with harvesttools, but that's an issue for a different repo :)
in the past i've used the gui on a mac, but i'm wanting to run it all on linux so i can incorporate it into pipelines in the future.

thanks for the clarification.
