### ISSUE TITLE
Genome file extensions not checked

### ISSUE THREAD

**Issue by chrisgulvik** [marbl/parsnp#15]
When genomes are *.fna, parsnp indicates the genome files are '|->[OK]', however this does not check for the file extension expected (only *.fasta ?). Parsnp dies without explaining the file ext(s) are unrecognized as FastA format, instead printing 'IndexError: string index out of range'. A lucid error msg here would be helpful, perhaps indicating which extensions are accepted.

This might fix Issue #12.

Example:
	$ parsnp -r ~/NC_013315.fna -g ~/NC_013315.gbk -c -u -v -d ~/PARSNP/027 -p 30 -o ~/PARSNP/027_out | tee -a ~/PARSNP/027/parsnp.log

|--Parsnp v1.2--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest
-->Reading Genome (asm, fasta) files from /home/PARSNP/027..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) /home/NC_013315.gbk..
  |->[OK]
Traceback (most recent call last):
  File "<string>", line 656, in <module>
.******************************************************************************
SETTINGS:
|-refgenome:	/home/NC_013315.fna
|-aligner:	libMUSCLE
|-seqdir:	/home/PARSNP/027
|-outdir:	/home/PARSNP/027_out
|-OS:		Linux
|-threads:	30
.******************************************************************************

<<Parsnp started>>

IndexError: string index out of range

**Comment by treangen** [comment]
hello,

>Parsnp dies without explaining the file ext(s) are unrecognized as FastA format

thanks for posting. just to clarify, the reference genome (if specified with -r) must be in fasta format. there is no requirement w.r.t an arbitrary extension (fna, fasta, or otherwise).

>-r ~/NC_013315.fna -g ~/NC_013315.gbk 

The issue is the above combination of parameters, the first reference gets parsed OK, but then another reference is expected in the provided genbank file. My guess is that it the genbank file you provided does not contain a reference, only annotations. If this is not the case (i.e. it contains a reference genome at the end), please let me know. Providing a reference with -r and annotations (no reference) with -g is not currently supported, but I think it would be a useful feature to add, given this is a fairly common issue.

>A lucid error msg here would be helpful

100% agreed
